spring:
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:dev}"

logging:
  config: "classpath:logback-spring.xml"
  file: "${LOG_FILE:smart-floor}"
  folder: "${LOG_PATH:./logs}"

connector:
  tuya:
    ak: "${TUYA_AK:}"
    sk: "${TUYA_SK:}"
    region: "${TUYA_REGION:EU}"
    device_ids: "${TUYA_DEVICE_IDS:}"
    user_uid: "${TUYA_USER_UID:}"
  solarman:
    region: "${SOLARMAN_REGION:IN}"
    appid: "${SOLARMAN_APP_ID:}"
    secret: "${SOLARMAN_SECRET:}"
    username: "${SOLARMAN_USER_NAME:}"
    password: "${SOLARMAN_PASS:}"
    passhash: "${SOLARMAN_PASS_HASH:}"
    logger_sn: "${SOLARMAN_LOGGER_SN:}"
smart:
  tuya:
    temp_set:
      min: "${TUYA_TEMP_SET_MIN:5}"
      max: "${TUYA_TEMP_SET_MAX:24}"
    category_for_control_powers: "${TUYA_CATEGORY_FOR_CONTROL_POWERS:wk}"
  solarman:
    timeout_sec: "${SOLARMAN_TIMEOUT_SEC:600}"
    bms_soc:
      min: "${SOLARMAN_BMS_SOC_MIN:87.0}"
      mфч: "${SOLARMAN_BMS_SOC_MAX:95.0}"
      alarm_warn: "${SOLARMAN_BMS_SOC_ALARM_WARN:80.0}"
      alarm_error: "${SOLARMAN_BMS_SOC_ALARM_ERROR:59.0}"

